// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockNotificationWarning.Db;

#nullable disable

namespace StockNotificationWarning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812083104_SeedProductDetails")]
    partial class SeedProductDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockNotificationWarning.Entities.ProductDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ShopifyProductGid")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 12, 8, 31, 3, 709, DateTimeKind.Utc).AddTicks(4315),
                            CustomDescription = "This is a detailed description for the newest product.",
                            CustomDisplayName = "My Newest Product",
                            ShopifyProductGid = "gid://shopify/Product/8858179666170"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 12, 8, 31, 3, 709, DateTimeKind.Utc).AddTicks(4627),
                            CustomDescription = "Comfortable sneakers for everyday use.",
                            CustomDisplayName = "Patike",
                            ShopifyProductGid = "gid://shopify/Product/8858181271802"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 12, 8, 31, 3, 709, DateTimeKind.Utc).AddTicks(4632),
                            CustomDescription = "Premium boots for winter season.",
                            CustomDisplayName = "Cizme Model X",
                            ShopifyProductGid = "gid://shopify/Product/8861054828794"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 12, 8, 31, 3, 709, DateTimeKind.Utc).AddTicks(4634),
                            CustomDescription = "Keep an eye on inventory for this one!",
                            CustomDisplayName = "My New Low Stock Product",
                            ShopifyProductGid = "gid://shopify/Product/8861090283770"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 12, 8, 31, 3, 709, DateTimeKind.Utc).AddTicks(4637),
                            CustomDescription = "A classic design with modern comfort.",
                            CustomDisplayName = "Soko",
                            ShopifyProductGid = "gid://shopify/Product/8861082714362"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
